# Generated by Django 4.0.2 on 2022-08-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('selected_properties', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'ContactMe',
            },
        ),
    ]
